os: linux
dist: xenial
language: generic

services:
  - docker

before_install:
  - docker pull fr3akyphantom/droid-builder:latest
  - apt-get update && apt-get -y install repo
  - cd $HOME && mkdir android

before_script:
  - cd $HOME/android
  - repo init -u https://github.com/ResurrectionRemix/platform_manifest.git -b pie
  - repo sync -f --force-sync --no-clone-bundle
  - cp $TRAVIS_BUILD_DIR/* .

script:
  - cd $HOME/android
  - docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/builder/:rw,z" fr3akyphantom/droid-builder bash << EOF
  - cd /home/builder/
  - source build/envsetup.sh
  - # Choose build flavor as "eng" or "userdebug"
  - BUILD_FLAVOR="eng"
  - lunch omni_k7000-${BUILD_FLAVOR}
  - make -j$(nproc --all) recoveryimage
  - exit
  - EOF

deploy:
  strategy: git
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: $HOME/android/out
