os: linux
dist: xenial
language: generic

services:
  - docker

before_install:
  - docker pull fr3akyphantom/droid-builder:latest
  - cd $HOME && mkdir android

before_script:
  - cd $HOME/android
  - repo init -u https://github.com/ResurrectionRemix/platform_manifest.git -b pie
  - repo sync -f --force-sync --no-clone-bundle
  - cp $TRAVIS_BUILD_DIR/* .

script:
  - cd $HOME/android
  - . build/envsetup.sh && brunch k7000
  - make recoveryimage

deploy:
  strategy: git
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: $HOME/android/out
