version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - run: curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod +x ~/bin/repo && export PATH=~/bin:$PATH
      - run: repo init -u https://github.com/ResurrectionRemix/platform_manifest.git -q -b pie
      - restore_cache:
          keys:
           - android-repo-cache
      - run: repo sync
      - save_cache:
          key: android-repo-cache
          paths:
            - .repo/
      - checkout
      - run: echo "Hello world!"
