version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      #- restore_cache:
      #    keys:
      #      - python3.6
      #- run: bash -c "[ ! -d python3.6_src ] && mkdir python3.6_src && curl https://www.python.org/ftp/python/3.6.10/Python-3.6.10.tgz | tar -xz -C python3.6_src" || echo "Schon vorhanden"
      #- run: bash -c "cd python3.6_src/Python-3.6.10; ls && pwd; ./configure && make -j 4 && sudo make install"
      #- save_cache:
      #    key: python3.6
      #    paths:
      #      - python3.6_src
      - run: sudo bash -c "echo yes | add-apt-repository ppa:deadsnakes/ppa && apt-get update && apt-get -y install python3.6"
      - run: bash -c "[ ! -d ~/bin ] && mkdir ~/bin" || echo "Schon vorhanden"
      - run: curl https://storage.googleapis.com/git-repo-downloads/repo-1 > ~/bin/repo > ~/bin/repo && chmod +x ~/bin/repo && export PATH=~/bin:$PATH
      - run: git config --global user.email "noreply@downloader" && git config --global user.name "downloader"
      - run: repo init -u https://github.com/ResurrectionRemix/platform_manifest.git -q -b pie
      - restore_cache:
          keys:
           - android-repo-cache
      - run: repo sync
      - save_cache:
          key: android-repo-cache
          paths:
            - .repo/
      - checkout
      - run: echo "Hello world!"
